--Auto-generated by the Load Impact converter

local sleep_time = 10
local response
response = http.request({
  url="http://178.62.97.13/treasurehunt/api/createteam",
  method="POST",
  response_body_bytes=200000
})
client.sleep(sleep_time)

response = http.request({
  url="http://178.62.97.13/treasurehunt/api/assignteamleader",
  method="POST",
  headers={ ["Content-Type"]="application/json" },
  data="{ \"teamid\": \"8724\", \"playername\": \"bgerard\" }",
  response_body_bytes=200000
})
client.sleep(sleep_time)

response = http.request({
  url="http://178.62.97.13/treasurehunt/api/jointeam",
  method="POST",
  headers={ ["Content-Type"]="application/json" },
  data="{ \"teamid\": \"8724\", \"playername\": \"bgerard2\" }",
  response_body_bytes=200000
})
client.sleep(sleep_time)

response = http.request({
  url="http://178.62.97.13/treasurehunt/api/addqrcode",
  method="POST",
  headers={ ["Content-Type"]="application/json" },
  data="{ \"qrcode\": \"test\" }",
  response_body_bytes=200000
})
client.sleep(sleep_time)

response = http.request({
  url="http://178.62.97.13/treasurehunt/api/removeteam",
  method="DELETE",
  headers={ ["Content-Type"]="application/json" },
  data="{ \"teamid\": \"1126\" }",
  response_body_bytes=200000
})
client.sleep(sleep_time)

response = http.request({
  url="http://178.62.97.13/treasurehunt/api/removeplayer",
  method="DELETE",
  headers={ ["Content-Type"]="application/json" },
  data="{\"playername\": \"bgerard\" }",
  response_body_bytes=200000
})
client.sleep(sleep_time)

response = http.request({
  url="http://178.62.97.13/treasurehunt/api/updateplayerlocation",
  method="POST",
  headers={ ["Content-Type"]="application/json" },
  data="{ \"playername\": \"bgerard\", \"location\": \"test\",\"token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFtX2lkIjoiODcyNCIsImlhdCI6MTQ4Nzc4MTU1NH0._CX6F8QKjUq4dxbnAtMjW45pHjRev4PEcsbOSWcoZAk\"}",
  response_body_bytes=200000
})
client.sleep(sleep_time)

response = http.request({
  url="http://178.62.97.13/treasurehunt/api/gettoken",
  method="POST",
  headers={ ["Content-Type"]="application/json" },
  data="{ \"teamid\": \"8724\"}",
  response_body_bytes=200000
})
client.sleep(sleep_time)

response = http.request({
  url="http://178.62.97.13/treasurehunt/api/updateteamscore",
  method="POST",
  headers={ ["Content-Type"]="application/json" },
  data="{ \"playername\":\"bgerard\", \"teamid\": \"8724\", \"token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFtX2lkIjoiODcyNCIsImlhdCI6MTQ4Nzc4MTU1NH0._CX6F8QKjUq4dxbnAtMjW45pHjRev4PEcsbOSWcoZAk\", \"score\":\"1\"}",
  response_body_bytes=200000
})
client.sleep(sleep_time)

response = http.request({
  url="http://178.62.97.13/treasurehunt/api/getteamdetails",
  method="POST",
  headers={ ["Content-Type"]="application/json" },
  data="{ \"playername\":\"bgerard\", \"teamid\": \"8724\", \"token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFtX2lkIjoiODcyNCIsImlhdCI6MTQ4Nzc4MTU1NH0._CX6F8QKjUq4dxbnAtMjW45pHjRev4PEcsbOSWcoZAk\"}",
  response_body_bytes=200000
})
client.sleep(sleep_time)

response = http.request({
  url="http://178.62.97.13/treasurehunt/api/getallteamscores",
  method="POST",
  headers={ ["Content-Type"]="application/json" },
  data="{ \"playername\":\"bgerard\", \"token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFtX2lkIjoiODcyNCIsImlhdCI6MTQ4Nzc4MTU1NH0._CX6F8QKjUq4dxbnAtMjW45pHjRev4PEcsbOSWcoZAk\"}",
  response_body_bytes=200000
})
client.sleep(sleep_time)
